python train.py \
    --input_path /path/to/Target_Category \
    --model_path /path/to/model_directory \
    --lr 1e-5 \
    --bsz 4 \
    --epoch 5 \
    --grad_acc 1 \
    --grad_clip 1.0 \
    --seed 0 \
    --cuda 0 \
